remote_theme: mmistakes/so-simple-theme
title: This is the tittle from _config.yml
description: Mark Soro projects, codes and modules for Programming for Data Science with Python from Udacity. Learn Numpy and Pandas and advance SQL.
baseurl: 
github_username: m-soro
author: Mark Soro
image: 
plugins:
  - jemoji
  - jekyll-seo-tag
ga_tracking: 
